receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4311

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  prometheus:
    endpoint: 0.0.0.0:8761
    # namespace: ltg
    const_labels:
      app: app1
    send_timestamps: true
    metric_expiration: 10m
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    
processors:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: service_id
        value: 1
      - action: insert
        key: service_instance
        from_attribute: service.instance.id
      - action: insert
        key: loki.resource.labels
        value: service_name, service_instance, service_id
  attributes:
    actions:
      - action: insert
        key: log_file_name
        from_attribute: log.file.name
      - action: insert
        key: loki.attribute.labels
        value: log_file_name
        
extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [resource, attributes]
      exporters: [loki]
