apiVersion: 1
      
datasources:
  - name: p1
    type: prometheus
    uid: p1
    access: proxy
    orgId: 1
    url: http://prometheus1:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: p2
    type: prometheus
    uid: p2
    access: proxy
    orgId: 1
    url: http://prometheus2:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: pf
    type: prometheus
    uid: pf
    access: proxy
    orgId: 1
    url: http://prometheus-federated:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['service.instance.id', 'service.name'] # default: 'job', 'instance', 'pod', 'namespace'
        mappedTags: [{ key: 'service.name', value: 'service_name' }, { key: 'service.instance.id', value: 'service_instance' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: pf
      serviceMap:
        datasourceUid: pf
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceid":\s?"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'