{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Current Business Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(app) (business_wellness)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Business Wellness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PF-BusinessWellness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by(app) (business_wellness)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P1-BusinessWellness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(kind) (business_wellness)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2-BusinessWellness",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "max by(kind) (business_wellness)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basics (Up)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PF-Up",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P1-Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P2-Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}