global:
  scrape_interval: 1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: federation
    scrape_interval: 1s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'
        - '{__name__=~"business_wellness.*"}'
        - '{__name__=~"issues_created_total.*"}'

    static_configs:
      - targets:
          - 'prometheus1:9090'
          - 'prometheus2:9090'